fix: stream close
libp2p/js-libp2p-mplex pull request #116
Opened 2020-10-21 13:26 UTC by jacobheun

This adds some more aggressive closures to streams on abort and reset. It was previously possible for unwritten streams to not properly end when aborted/reset, which would result in them not properly notifying libp2p/application code of the termination. This could also result in streams lingering.

I'd like to do some more clean up here but am reserving that for https://github.com/libp2p/js-libp2p-mplex/pull/115, which will create some breaking behavior.

This should also resolve part of https://github.com/libp2p/js-libp2p-mplex/pull/113.

2020-10-21 14:55 UTC, achingbrain requested changes
LGTM, just some minor nits.

2020-10-21 14:55 UTC, achingbrain commented on src/stream.js
> +      abortController.abort(err)
`AbortController.abort` doesn't take any arguments - https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

2020-10-21 14:55 UTC, achingbrain commented on test/stream.spec.js
> +    const stream = createStream({ id, name, onEnd: () => deferred.resolve(), send: mockSend })
There should be an assertion here that the correct error was received.

2020-10-21 14:55 UTC, achingbrain commented on test/stream.spec.js
> +    const stream = createStream({ id, name, onEnd: () => deferred.resolve(), send: mockSend })
There should be an assertion here that the correct error was received.

2020-10-21 15:34 UTC, jacobheun commented
Added the assertions and removed the unused error param from the abort call, should be good now.

2020-10-22 11:07 UTC, achingbrain approved these changes

2020-10-22 11:10 UTC, merged